# Generated by Django 3.1.5 on 2021-01-18 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('Technology', 'Technology'), ('Exercise', 'Exercise'), ('Beauty', 'Beauty'), ('Engineering', 'Engineering'), ('Movies', 'Movies'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle '), ('Sports', 'Sports'), ('Music', 'Music')], max_length=100, null=True)),
                ('category_level', models.CharField(choices=[('1', 'First level category'), ('2', 'Second level category'), ('3', 'Third level category')], max_length=100, null=True)),
                ('add_time', models.DateTimeField(auto_now=True, help_text='Category add time', verbose_name='Category add time')),
                ('thumbnail', models.ImageField(null=True, upload_to='media/')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_category', to='material.category', verbose_name='Parent category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=500, verbose_name='Post title')),
                ('sub_title', models.CharField(blank=True, help_text='Subtitle', max_length=500, null=True, verbose_name='Subtitle')),
                ('content', models.TextField(max_length=10000)),
                ('is_published', models.BooleanField(default=False, verbose_name='Post Published')),
                ('click_num', models.IntegerField(default=0, verbose_name='Number of clicks')),
                ('like_num', models.IntegerField(default=0, verbose_name='Number of likes')),
                ('dislike_num', models.IntegerField(default=0, verbose_name='Number of dislikes')),
                ('comment_num', models.IntegerField(default=0, verbose_name='Number of comments')),
                ('add_time', models.DateTimeField(auto_now=True, help_text='Post add time', verbose_name='Post add time')),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='material.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=100, verbose_name='Tag name')),
                ('add_time', models.DateTimeField(auto_now=True, help_text='Tag add time', verbose_name='Tag add time')),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True, help_text='post tag add time', verbose_name='Post tag add time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.tag')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='material.PostTag', to='material.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
